#include "FTGameplayTags.h"

UE_DEFINE_GAMEPLAY_TAG(TAG_FT_Event_RaidStarted, "Event.Raid.Started");
UE_DEFINE_GAMEPLAY_TAG(TAG_FT_Event_RaidFailed, "Event.Raid.Failed");
UE_DEFINE_GAMEPLAY_TAG(TAG_FT_Event_RaidEscaped, "Event.Raid.Escaped");
UE_DEFINE_GAMEPLAY_TAG(TAG_FT_Event_ItemPickedUp, "Event.Item.PickedUp");
UE_DEFINE_GAMEPLAY_TAG(TAG_FT_Event_ItemConsumed, "Event.Item.Consumed");
UE_DEFINE_GAMEPLAY_TAG(TAG_FT_Event_ReportGaugeChanged, "Event.ReportGauge.Changed");
UE_DEFINE_GAMEPLAY_TAG(TAG_FT_Event_SecurityCalled, "Event.Security.Called");
UE_DEFINE_GAMEPLAY_TAG(TAG_FT_Event_ObjectiveCompleted, "Event.Objective.Completed");
UE_DEFINE_GAMEPLAY_TAG(TAG_FT_Event_NPCDetectedPlayer, "Event.NPC.DetectedPlayer");
UE_DEFINE_GAMEPLAY_TAG(TAG_FT_Event_NPCReportStarted, "Event.NPC.ReportStarted");
UE_DEFINE_GAMEPLAY_TAG(TAG_FT_Event_NPCReportProgress, "Event.NPC.ReportProgress");
UE_DEFINE_GAMEPLAY_TAG(TAG_FT_Event_NPCReportCompleted, "Event.NPC.ReportCompleted");
UE_DEFINE_GAMEPLAY_TAG(TAG_FT_Event_SecurityAttackStarted, "Event.Security.AttackStarted");
UE_DEFINE_GAMEPLAY_TAG(TAG_FT_Event_SecurityTargetCaptured, "Event.Security.TargetCaptured");
UE_DEFINE_GAMEPLAY_TAG(TAG_FT_Event_SecurityTargetEscaped, "Event.Security.TargetEscaped");
UE_DEFINE_GAMEPLAY_TAG(TAG_FT_Event_SecurityTargetSeen, "Event.Security.TargetSeen");
UE_DEFINE_GAMEPLAY_TAG(TAG_FT_Event_SecurityTargetLost, "Event.Security.TargetLost");
UE_DEFINE_GAMEPLAY_TAG(TAG_FT_Event_SecurityChaseGaugeChanged, "Event.Security.ChaseGauge.Changed");
UE_DEFINE_GAMEPLAY_TAG(TAG_FT_Event_SecurityChaseEnded, "Event.Security.ChaseEnded");
UE_DEFINE_GAMEPLAY_TAG(TAG_FT_Event_SecurityDeployed, "Event.Security.Deployed");
UE_DEFINE_GAMEPLAY_TAG(TAG_FT_Event_SecurityReturnedToRoom, "Event.Security.ReturnedToRoom");
UE_DEFINE_GAMEPLAY_TAG(TAG_FT_Event_ShelfDamaged, "Event.Shelf.Damaged");
UE_DEFINE_GAMEPLAY_TAG(TAG_FT_Event_ShelfDestroyed, "Event.Shelf.Destroyed");
UE_DEFINE_GAMEPLAY_TAG(TAG_FT_Request_DropItem, "Gameplay.Request.DropItem");
