

[/Script/CommonUI.CommonUISettings]
CommonButtonAcceptKeyHandling=TriggerClick

[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=06C869E548260C3B38C1EEAD95C6D53A

[/Script/ProjectFT.FTAssetManager]
GameDataPath=/Game/Data/Game/DA_FTGameData.DA_FTGameData

[/Script/Engine.AssetManagerSettings]
; -PrimaryAssetTypesToScan=(PrimaryAssetType="Map",AssetBaseClass=/Script/Engine.World,bHasBlueprintClasses=False,bIsEditorOnly=True,Directories=((Path="/Game/Maps")),SpecificAssets=,Rules=(Priority=-1,ChunkId=-1,bApplyRecursively=True,CookRule=Unknown))
; -PrimaryAssetTypesToScan=(PrimaryAssetType="PrimaryAssetLabel",AssetBaseClass=/Script/Engine.PrimaryAssetLabel,bHasBlueprintClasses=False,bIsEditorOnly=True,Directories=((Path="/Game")),SpecificAssets=,Rules=(Priority=-1,ChunkId=-1,bApplyRecursively=True,CookRule=Unknown))
+PrimaryAssetTypesToScan=(PrimaryAssetType="Map",AssetBaseClass="/Script/Engine.World",bHasBlueprintClasses=False,bIsEditorOnly=True,Directories=((Path="/Game/Maps")),SpecificAssets=,Rules=(Priority=-1,ChunkId=-1,bApplyRecursively=True,CookRule=Unknown))
+PrimaryAssetTypesToScan=(PrimaryAssetType="PrimaryAssetLabel",AssetBaseClass="/Script/Engine.PrimaryAssetLabel",bHasBlueprintClasses=False,bIsEditorOnly=True,Directories=((Path="/Game")),SpecificAssets=,Rules=(Priority=-1,ChunkId=-1,bApplyRecursively=True,CookRule=Unknown))
bOnlyCookProductionAssets=False
bShouldManagerDetermineTypeAndName=False
bShouldGuessTypeAndNameInEditor=True
bShouldAcquireMissingChunksOnLoad=False
bShouldWarnAboutInvalidAssets=True
MetaDataTagsForAssetRegistry=()

[/Script/LevelDataAssetGenerator.LevelDataAssetGeneratorSettings]
GeneratedDataAssetClass=/Script/ProjectFT.FTLevelPreloadDataAsset
OutputFolder=(Path="/Game/Blueprints/LevelPreload")
GeneratedAssetPrefix=DA_LevelPreload_
LevelPropertyName=Level
LevelIdPropertyName=LevelId
GeneratedEnvironmentAssetsPropertyName=GeneratedEnvironmentAssets
GeneratedRuntimeAssetsPropertyName=GeneratedRuntimeAssets
bUseInventoryPreloadDataAssetPropertyName=bUseInventoryPreloadDataAsset
InventoryPreloadDataAssetPropertyName=InventoryPreloadDataAsset
InventoryPreloadDataAssetClass=/Script/ProjectFT.FTInventoryPreloadDataAsset
InventoryPreloadOutputFolder=(Path="/Game/Generated/LevelPreload")
InventoryPreloadAssetName=DA_InventoryPreload_Default
InventoryItemAssetsPropertyName=InventoryItemAssets
bIncludeAllPrimaryItemAssetsPropertyName=bIncludeAllPrimaryItemAssets
bAssignInventoryPreloadToLevelDataAssets=True
InventoryItemDataDirectory=(Path="/Game/Blueprints/Items/Data")
InventoryItemDataAssetClass=/Script/ProjectFT.FTItemDataAsset
+PlayLevelIds=Lvl_Main
+PlayLevelIds=Market_Test
+PlayLevelIds=Lvl_MarketA
+PlayLevelIds=Lvl_MarketB
+HubLevelIds=Lvl_Hub
+MainMenuLevelIds=Lvl_MainMenu
PlayFeatures=(bUseInventory=True,bUseShelf=True,bUseCombat=True,bUseDamageText=True,bUseAI=True,bUseCrafting=False,bUseShop=False,bUseMarket=False,bUseStorage=False,bUseQuest=True,bUseMainMenu=False)
HubFeatures=(bUseInventory=True,bUseShelf=False,bUseCombat=False,bUseDamageText=False,bUseAI=False,bUseCrafting=True,bUseShop=True,bUseMarket=True,bUseStorage=True,bUseQuest=True,bUseMainMenu=False)
MainMenuFeatures=(bUseInventory=False,bUseShelf=False,bUseCombat=False,bUseDamageText=False,bUseAI=False,bUseCrafting=False,bUseShop=False,bUseMarket=False,bUseStorage=False,bUseQuest=False,bUseMainMenu=True)
+CommonRuntimeAssetDirectories=(Path="/Game/UI/Loading")
+HUDDirectories=(Path="/Game/UI/HUD")
+HUDDirectories=(Path="/Game/UI/Inventory")
+ShelfDirectories=(Path="/Game/Blueprints/Shelf")
+ShelfDirectories=(Path="/Game/Blueprints/Player")
+CombatDirectories=(Path="/Game/Blueprints/Items/Data")
+CombatDirectories=(Path="/Game/Blueprints/Items/GE")
+CombatDirectories=(Path="/Game/Blueprints/Weapon")
+DamageTextAssets=/Game/UI/WBP_DamageText.WBP_DamageText
+AIDirectories=(Path="/Game/Blueprints/NPC")
+CraftingDirectories=(Path="/Game/UI/Hub")
+ShopDirectories=(Path="/Game/UI/Hub")
+MarketDirectories=(Path="/Game/UI/Hub")
+StorageDirectories=(Path="/Game/UI/Hub")
+StorageDirectories=(Path="/Game/UI/Inventory")
+StorageDirectories=(Path="/Game/Blueprints/Hub")
+QuestDirectories=(Path="/Game/UI/Hub")
+QuestDirectories=(Path="/Game/UI/HUD")
+MainMenuDirectories=(Path="/Game/UI/Menu")
bExpandRuntimeDependencies=True
bIgnoreEngineAssets=True
bIgnorePluginAssets=True
bIncludeStaticMeshComponent=True
bIncludeInstancedStaticMeshComponent=True
bIncludeHierarchicalInstancedStaticMeshComponent=True
bIncludePlacedEnvironmentAssets=False

[/Script/UnrealEd.ProjectPackagingSettings]
Build=IfProjectHasCode
BuildConfiguration=PPBC_Development
BuildTarget=
FullRebuild=False
ForDistribution=False
IncludeDebugFiles=False
BlueprintNativizationMethod=Disabled
bIncludeNativizedAssetsInProjectGeneration=False
bExcludeMonolithicEngineHeadersInNativizedCode=False
UsePakFile=True
bUseIoStore=True
bUseZenStore=False
bMakeBinaryConfig=False
bGenerateChunks=False
bGenerateNoChunks=False
bChunkHardReferencesOnly=False
bForceOneChunkPerFile=False
MaxChunkSize=0
bBuildHttpChunkInstallData=False
HttpChunkInstallDataDirectory=(Path="")
WriteBackMetadataToAssetRegistry=Disabled
bWritePluginSizeSummaryJsons=False
bCompressed=True
PackageCompressionFormat=Oodle
bForceUseProjectCompressionFormatIgnoreHardwareOverride=False
PackageAdditionalCompressionOptions=
PackageCompressionMethod=Kraken
PackageCompressionLevel_DebugDevelopment=4
PackageCompressionLevel_TestShipping=4
PackageCompressionLevel_Distribution=7
PackageCompressionMinBytesSaved=1024
PackageCompressionMinPercentSaved=5
bPackageCompressionEnableDDC=False
PackageCompressionMinSizeToConsiderDDC=0
HttpChunkInstallDataVersion=
IncludePrerequisites=True
IncludeAppLocalPrerequisites=False
bShareMaterialShaderCode=True
bDeterministicShaderCodeOrder=False
bSharedMaterialNativeLibraries=True
ApplocalPrerequisitesDirectory=(Path="")
IncludeCrashReporter=False
InternationalizationPreset=English
-CulturesToStage=en
+CulturesToStage=en
LocalizationTargetCatchAllChunkId=0
bCookAll=False
bCookMapsOnly=False
bTreatWarningsAsErrorsOnCook=False
bSkipEditorContent=False
bSkipMovies=False
-IniKeyDenylist=KeyStorePassword
-IniKeyDenylist=KeyPassword
-IniKeyDenylist=DebugKeyStorePassword
-IniKeyDenylist=DebugKeyPassword
-IniKeyDenylist=rsa.privateexp
-IniKeyDenylist=rsa.modulus
-IniKeyDenylist=rsa.publicexp
-IniKeyDenylist=aes.key
-IniKeyDenylist=SigningPublicExponent
-IniKeyDenylist=SigningModulus
-IniKeyDenylist=SigningPrivateExponent
-IniKeyDenylist=EncryptionKey
-IniKeyDenylist=DevCenterUsername
-IniKeyDenylist=DevCenterPassword
-IniKeyDenylist=IOSTeamID
-IniKeyDenylist=SigningCertificate
-IniKeyDenylist=MobileProvision
-IniKeyDenylist=AppStoreConnectKeyPath
-IniKeyDenylist=AppStoreConnectIssuerID
-IniKeyDenylist=AppStoreConnectKeyID
-IniKeyDenylist=IniKeyDenylist
-IniKeyDenylist=IniSectionDenylist
+IniKeyDenylist=KeyStorePassword
+IniKeyDenylist=KeyPassword
+IniKeyDenylist=DebugKeyStorePassword
+IniKeyDenylist=DebugKeyPassword
+IniKeyDenylist=rsa.privateexp
+IniKeyDenylist=rsa.modulus
+IniKeyDenylist=rsa.publicexp
+IniKeyDenylist=aes.key
+IniKeyDenylist=SigningPublicExponent
+IniKeyDenylist=SigningModulus
+IniKeyDenylist=SigningPrivateExponent
+IniKeyDenylist=EncryptionKey
+IniKeyDenylist=DevCenterUsername
+IniKeyDenylist=DevCenterPassword
+IniKeyDenylist=IOSTeamID
+IniKeyDenylist=SigningCertificate
+IniKeyDenylist=MobileProvision
+IniKeyDenylist=AppStoreConnectKeyPath
+IniKeyDenylist=AppStoreConnectIssuerID
+IniKeyDenylist=AppStoreConnectKeyID
+IniKeyDenylist=IniKeyDenylist
+IniKeyDenylist=IniSectionDenylist
-IniSectionDenylist=HordeStorageServers
-IniSectionDenylist=StorageServers
-IniSectionDenylist=/Script/AndroidFileServerEditor.AndroidFileServerRuntimeSettings
+IniSectionDenylist=HordeStorageServers
+IniSectionDenylist=StorageServers
+IniSectionDenylist=/Script/AndroidFileServerEditor.AndroidFileServerRuntimeSettings
+MapsToCook=(FilePath="/Game/Level/Lvl_Hub")
+MapsToCook=(FilePath="/Game/Level/Lvl_MarketA")
+MapsToCook=(FilePath="/Game/Level/Lvl_MarketB")
+MapsToCook=(FilePath="/Game/Level/Lvl_Loading")
+MapsToCook=(FilePath="/Game/Level/Lvl_MainMenu")
+DirectoriesToAlwaysCook=(Path="/NNEDenoiser")
bRetainStagedDirectory=False
CustomStageCopyHandler=

