#pragma once

#include "CoreMinimal.h"

DECLARE_LOG_CATEGORY_EXTERN(LogFTCore, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogFTUI, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogFTItem, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogFTAsset, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogFTNPC, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogFTFlow, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogFTPlayer, Log, All);
