#include "FTLogChannels.h"

DEFINE_LOG_CATEGORY(LogFTCore);
DEFINE_LOG_CATEGORY(LogFTUI);
DEFINE_LOG_CATEGORY(LogFTItem);
DEFINE_LOG_CATEGORY(LogFTAsset);
DEFINE_LOG_CATEGORY(LogFTNPC);
DEFINE_LOG_CATEGORY(LogFTFlow);
